[package]
name = "bevy_terrain"
version = "0.1.0"
edition = "2021"

[features]
default = [
    # "bevy/dynamic",
]

[dependencies]
bevy = { git="https://github.com/bevyengine/bevy" }
bevy-inspector-egui = { git="https://github.com/jakobhellermann/bevy-inspector-egui" }

wgpu = "0.12.0"
itertools = "*"
bytemuck = "*"
image = "*"
lru = "*"
bitflags = "*"
