[package]
name = "bevy_terrain"
version = "0.1.0"
edition = "2021"

[features]
default = []

[dependencies]
bevy = { git = "https://github.com/ku95/bevy", branch = "texture-formats" }
# bevy-inspector-egui = { git="https://github.com/jakobhellermann/bevy-inspector-egui" }

ndarray = "*"
itertools = "*"
image = "*"
lru = "*"
bitflags = "*"
strum = "*"
strum_macros = "*"
ron = { version = "*", features = ["indexmap"] }
