[package]
name = "bevy_terrain"
version = "0.1.0"
edition = "2021"

[features]
default = [
    # "bevy/dynamic",
]

[dependencies]
bevy = "0.6.0"
bevy-inspector-egui = "0.7.2"


itertools = "0.10"
bytemuck = "1.7.3"
image = "0.23.14"
lru = "0.7.2"

